<script>import { setContext } from 'svelte';
export let config;
setContext('rockabilityConfig', config);
</script>

<slot />

<style>:root {
  font-family: Arial, Helvetica, "Trebuchet MS", sans-serif;
  --font-color: #000;
  --bg-color: #fff;
  --font-size: default;
  --line-height: default;
  --letter-spacing: default;
  --word-spacing: default;
  --paragraph-spacing: 1em;
  --text-align: left;
  --button-padding: 5px 10px;
  --button-border-radius: 4px;
  --unit-box-bg: lightgray;
  --custom-select-placeholder-color: #a9a9a9;
  --full-image-overlay: rgba(0, 0, 0, 0.5);
  --full-image-font: #fff;
  --full-image-font-outline: #000;
  --full-image-font-outline-width: 1px;
  --slider-pagination-active-color: rgb(5, 151, 41);
  --slider-pagination-inactive-color: #eee;
  --slider-pagination-bullet-border: 1px solid;
  --slider-pagination-bullet-border-color: #888;
  --modal-margin: 20px auto;
  --modal-backdrop-color: rgba(0, 0, 0, 0.5);
  --modal-border: 1px solid;
  --modal-border-radius: 4px;
  --modal-border-color: black;
  --modal-heading-border: 1px solid;
  --modal-heading-border-color: black;
  --modal-padding-content: 10px;
  --modal-padding-header: 10px;
  --primary-color: #000;
  --primary-bg: rgb(148, 245, 162);
  --primary-border: 1px solid;
  --primary-border-color: rgb(80, 160, 130);
  --primary-color-hover: rgb(48, 96, 78);
  --primary-bg-hover: #fff;
  --secondary-color: #fff;
  --secondary-bg: rgb(120, 40, 111);
  --secondary-border: 1px solid;
  --secondary-border-color: rgb(160, 80, 151);
  --secondary-color-hover: rgb(120, 40, 111);
  --secondary-bg-hover: #fff;
  --outline: solid 2px;
  --outline-color: rgb(77, 144, 254);
  --link-color: rgb(0, 80, 200);
  --link-color-hover: rgb(0, 100, 20);
  --link-color-visited: rgb(0, 80, 200);
  --input-color: #000;
  --input-bg: #fff;
  --input-border: 1px solid;
  --input-border-color: #888;
  --input-border-radius: 4px;
  --input-disabled-color: dimgray;
  --input-disabled-bg: lightgray;
  --input-color-hover: #000;
  --input-bg-hover: rgb(230, 230, 230);
  --boolean-bg: #fff;
  --boolean-selected-color: rgb(65, 130, 240);
  --input-error-color: rgb(180, 0, 0);
  --input-error-font-size: 0.85em;
  --input-error-margin: 0 0 0 6px;
  --input-error-highlight: rgb(255, 235, 235);
  --alert-padding: 5px 10px;
  --alert-border-radius: 4px;
  --info-color: #000;
  --info-bg: rgb(173, 224, 255);
  --info-border: 1px solid;
  --info-border-color: #5f77ff;
  --success-color: #000;
  --success-bg: rgb(180, 230, 180);
  --success-border: 1px solid;
  --success-border-color: rgb(0, 160, 0);
  --warn-color: #000;
  --warn-bg: rgb(255, 255, 170);
  --warn-border: 1px solid;
  --warn-border-color: rgb(146, 144, 11);
  --error-color: #fff;
  --error-bg: rgb(180, 0, 0);
  --error-border: 1px solid;
  --error-border-color: rgb(150, 0, 0);
}</style>
