import { SvelteComponentTyped } from "svelte";
declare const __propDef: {
    props: {
        /**
             * A unique identifier used as a post fix for the html elements used in this component.
             * @required
             */ id?: string;
        /**
             * Specifies the name of an input element. If no labelText is assigned, the name property
             * will be used to generate a label text instead.
             * @required
             */ name?: string;
        /**
             * The value of the input element.
             */ value?: string;
        /**
             * Use this property to add custom classes and stylings to the component.
             */ className?: string;
        /**
             * Define the type of the input element. Valid types are:
             * email, text, url, search and tel
             */ type?: string;
        /**
             * Specifies whether the input element should have autocomplete enabled.
             */ autocomplete?: string;
        /**
             * Specifies that an input field must be filled out before submitting the form.
             */ required?: boolean;
        /**
             * Specifies that an input element should be disabled.
             */ disabled?: boolean;
        /**
             * Specifies a short hint that describes the expected value of an input element.
             */ placeholder?: string;
        /**
             * Specifies that an input field is read-only.
             */ readonly?: boolean;
        /**
             * Specifies a regular expression that an input element's value is checked against.
             */ pattern?: string;
        /**
             * Specifies the minimum number of characters required in an input element.
             */ minlength?: number;
        /**
             * Specifies the maximum number of characters allowed in an input element.
             */ maxlength?: number;
        /**
             * Specifies the form the input element belongs to. This is only required if the TextInput component
             * is not a child of any form element.
             */ form?: string;
        /**
             * Specifies the width, in characters, of an input element.
             */ size?: number;
        /**
             * Specifies that the text direction will be submitted.
             * Only valid for text and search input types.
             */ dirname?: string;
        /**
             * Specifies that a user can enter more than one value in an input element.
             * This works only when the type is set to 'email'. The user can then enter multiple emails by
             * separating theme with a comma.
             */ multiple?: boolean;
        /**
             * Refers to a datalist element that contains pre-defined options for an input element.
             * This property can be useful for input suggestions. Note that you only have to pass in a
             * string array. The dataset elements will be automatically generated by this component using
             * the value in the given array.
             */ list?: Array<string>;
        /**
             * Specify the text for the label. The label will be automatically generated for the input field.
             * If this property won't be specified, a default name will be generated based on the input type
             * and the given name property.
             */ labelText?: string;
        /**
             * Use this property to show or hide the label of an input element. If showLabel is set to false,
             * the corresponding input element will have an aria-label element with the labelText instead.
             */ showLabel?: boolean;
        /**
             * Use this property to specify if the label should be rendered before the input element or after the input element.
             * This property might come in handy for proper positioning of the label and input fields.
             * If positionLabelAfter equals true, first the input element is rendered, then the label element.
             */ positionLabelAfter?: boolean;
        /**
             * Use this property to provide an error message for this input field in case any validation failed.
             */ errorMessage?: string;
        /**
             * Use this property to show or hide the error of an input element.
             */ showError?: boolean;
    };
    events: {
        change: Event;
        blur: FocusEvent;
        focus: FocusEvent;
        input: Event;
        select: Event;
    } & {
        [evt: string]: CustomEvent<any>;
    };
    slots: {
        label: {};
        error: {};
    };
};
export declare type TextInputProps = typeof __propDef.props;
export declare type TextInputEvents = typeof __propDef.events;
export declare type TextInputSlots = typeof __propDef.slots;
export default class TextInput extends SvelteComponentTyped<TextInputProps, TextInputEvents, TextInputSlots> {
}
export {};
